"""Six promises about what a digest is allowed to depend on.

Two of these obligations are about a single line of code and two are about a
single word in a boolean. `_normalize_hash_content` folds CRLF to LF with one
`str.replace` behind a NUL gate, and the whole cross-platform story rests on
that being *one* pass rather than a loop: `b"\\r\\r\\n"` must come out as
`b"\\r\\n"` and not as `b"\\n"`, because the day someone "normalizes harder"
every existing lock for a file containing that byte pair silently rotates.
`providers.py` copies the same two lines into `PathHashProvider.resolve`
instead of calling the helper, so the exact facet and the raw boundary facet
canonicalize through two physically separate expressions that no assertion ties
together; a differential is the only thing that notices when one of them moves.
The corresponding pair on the slice side is `slice_availability_is_required`,
which any one member carrying an explicit `verify_facets` list turns on for the
whole slice, and the only thing standing between that and a hard usage exit is
the `slice_mode in slice_gated_facets` conjunct beside it.

Getting fixtures that reach those branches took more care than the assertions
did. `_normalize_hash_content` is never called directly by the existing suite -
every case arrives through `_read_path_content` - and the provider copy is
reached through file selection, so the differential needed a `ProviderContext`
built by hand with `read_file` closing over the generated bytes; that turns a
filesystem round trip into a function call and makes four hundred Hypothesis
examples affordable. A slice with a null member digest cannot be generated
strictly at all, because `_recompute_slice_entry` raises for a missing
boundary digest, so the availability table generates with `strict=False` and
pairs a `path-hash` component with a `leaf` one, which publishes no boundary
digest by declaration rather than by failure. And the slice-fingerprint
stability property runs against `_recompute_slice_entry` on synthetic entry
maps rather than real repositories, with a hand-written depth-first closure as
its oracle, because the claim being tested is about the consumers graph and not
about Git; four repository-level metamorphic tests sit beside it so the
synthetic version cannot drift away from what `generate` actually produces.

Two results here are findings rather than green ticks. The exclusivity of
`UNAVAILABLE FACET` and `SLICE MISMATCH` holds, but only because the
availability branch ends in `continue`, and the fixture proves the suppression
is real by asserting the locked and recomputed slice entries genuinely differ
before asserting the mismatch is absent. The second clause of OBL-HASHING-100
does not hold: `generate_lockfile` with `strict=True` accepts a slice naming a
component that does not exist and publishes a stable fingerprint over
`{"ghost": null, ...}`, because the `continue` for a missing entry runs before
the strict checks. Every lock-writing entry point rejects that config first, so
no user can reach it through the CLI or the public API, but the API call itself
does not. That is written as an expected failure with three tests pinning the
digest it currently produces, so a partial fix cannot pass unnoticed.

Covers OBL-HASHING-042, OBL-HASHING-092, OBL-HASHING-056, OBL-HASHING-100,
OBL-HASHING-063 and OBL-HASHING-104.
"""

from __future__ import annotations

import ast
import hashlib
import os
import unittest
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence, Set, Tuple

from hypothesis import HealthCheck, example, given, settings
from hypothesis import strategies as st

import boundver
from boundver._hashing import _normalize_hash_content, canonical_json, sha256_hex
from boundver._lockfile import _recompute_slice_entry, generate_lockfile
from boundver._utils import ConfigError
from boundver.providers import PathHashProvider, ProviderContext

from tests._parity import run_cli
from tests._scenarios import Scenario

PROFILE = settings(
    max_examples=400,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow],
)


# ---------------------------------------------------------------------------
# OBL-HASHING-042 - the line-ending rule, called directly
# ---------------------------------------------------------------------------

#: Every documented input to `_normalize_hash_content` and the exact bytes it
#: returned when probed. The last four rows are the ones that separate the
#: shipped rule from its plausible neighbours: a single pass, a NUL gate, and
#: no interest in a CR that is not followed by an LF.
NORMALIZATION: Dict[str, Tuple[bytes, bytes]] = {
    "CRLF in text": (b"one\r\ntwo\r\n", b"one\ntwo\n"),
    "bare LF": (b"one\ntwo\n", b"one\ntwo\n"),
    "empty content": (b"", b""),
    "NUL alone": (b"\x00", b"\x00"),
    "lone CR between letters": (b"one\rtwo", b"one\rtwo"),
    "CR at the end of content": (b"one\r", b"one\r"),
    "LF immediately followed by CR": (b"one\n\rtwo", b"one\n\rtwo"),
    "CRLF inside NUL-bearing content": (b"one\r\n\x00two\r\n", b"one\r\n\x00two\r\n"),
    "carriage return before a CRLF pair": (b"one\r\r\ntwo", b"one\r\ntwo"),
    "adjacent CRLF pairs": (b"\r\n\r\n", b"\n\n"),
}


def _until_stable(content: bytes) -> bytes:
    """The neighbour that folds repeatedly instead of once."""
    if b"\x00" in content:
        return content
    while b"\r\n" in content:
        content = content.replace(b"\r\n", b"\n")
    return content


def _without_nul_gate(content: bytes) -> bytes:
    """The neighbour that canonicalizes binary content too."""
    return content.replace(b"\r\n", b"\n")


def _disagreeing_rows(candidate) -> Set[str]:
    """Which table rows *candidate* answers differently from the shipped rule."""
    return {
        label
        for label, (raw, expected) in NORMALIZATION.items()
        if candidate(raw) != expected
    }


class LineEndingCanonicalizationTests(unittest.TestCase):
    """OBL-HASHING-042: one pass, gated on NUL, indifferent to a lone CR."""

    def test_every_documented_input_normalizes_to_the_recorded_bytes(self):
        for label, (raw, expected) in NORMALIZATION.items():
            with self.subTest(label):
                self.assertEqual(_normalize_hash_content(raw), expected)

    def test_a_carriage_return_before_a_crlf_pair_survives_the_single_pass(self):
        """The whole point of `str.replace` rather than a fixed-point loop."""
        self.assertEqual(_normalize_hash_content(b"one\r\r\ntwo"), b"one\r\ntwo")
        self.assertNotEqual(_normalize_hash_content(b"one\r\r\ntwo"), b"one\ntwo")

    def test_a_lone_carriage_return_is_left_exactly_where_it_was(self):
        """A classic-Mac line ending is content, not a line ending to fold."""
        self.assertEqual(_normalize_hash_content(b"one\rtwo"), b"one\rtwo")
        self.assertEqual(_normalize_hash_content(b"one\r"), b"one\r")

    def test_the_table_would_report_a_repeat_until_stable_normalizer(self):
        """Premise: the single-pass row is the one that discriminates, alone."""
        self.assertEqual(
            _disagreeing_rows(_until_stable),
            {"carriage return before a CRLF pair"},
        )

    def test_the_table_would_report_a_normalizer_missing_the_nul_gate(self):
        """Premise: the binary row is the one that discriminates, alone."""
        self.assertEqual(
            _disagreeing_rows(_without_nul_gate),
            {"CRLF inside NUL-bearing content"},
        )

    def test_the_table_reports_nothing_against_the_shipped_rule(self):
        """Premise for both of the above: the comparison is not always non-empty."""
        self.assertEqual(_disagreeing_rows(_normalize_hash_content), set())


# ---------------------------------------------------------------------------
# OBL-HASHING-092 - the copy inside PathHashProvider.resolve
# ---------------------------------------------------------------------------

#: The one selector the differential context declares. Its name reaches the
#: entry label, so it has to be a literal rather than a glob or the provider
#: would consult `list_files` for the answer instead of `read_file`.
DIFFERENTIAL_SELECTOR = "contract.txt"

#: The tokens the rule branches on. `st.binary()` alone almost never produces
#: a CRLF pair, so most of the corpus is assembled from these instead.
NORMALIZATION_TOKENS = (b"\r", b"\n", b"\r\n", b"\x00", b"a", b"bb")


def normalization_inputs() -> st.SearchStrategy:
    """Bytes dense in CR, LF and NUL, plus ordinary random bytes."""
    assembled = st.lists(
        st.sampled_from(NORMALIZATION_TOKENS), max_size=10
    ).map(b"".join)
    return st.one_of(assembled, st.binary(max_size=24))


def _provider_context(content: bytes) -> ProviderContext:
    """A context whose source accessor hands back exactly *content*."""
    return ProviderContext(
        repo_root=Path("."),
        component_path="svc",
        boundary_cfg={"provider": "path-hash", "paths": [DIFFERENTIAL_SELECTOR]},
        source="working-tree",
        read_file=lambda repo_rel: content,
        list_files=lambda prefix: [f"svc/{DIFFERENTIAL_SELECTOR}"],
    )


def _provider_entry_content(content: bytes) -> bytes:
    """What `PathHashProvider.resolve` would hand core for *content*."""
    resolved = PathHashProvider().resolve(_provider_context(content))
    if resolved.status != "ok" or len(resolved.entries) != 1:
        raise AssertionError(
            f"provider did not resolve {content!r}: "
            f"status={resolved.status} errors={resolved.errors}"
        )
    label, produced = resolved.entries[0]
    if label != f"file:{DIFFERENTIAL_SELECTOR}":
        raise AssertionError(f"unexpected entry label {label!r}")
    return bytes(produced)


class ProviderInlineNormalizationTests(unittest.TestCase):
    """OBL-HASHING-092: the duplicated rule must be the same rule."""

    @PROFILE
    @given(content=normalization_inputs())
    @example(content=b"one\r\ntwo\r\n")
    @example(content=b"one\rtwo")
    @example(content=b"one\r")
    @example(content=b"one\r\n\x00two\r\n")
    @example(content=b"one\r\r\ntwo")
    @example(content=b"")
    def test_the_provider_copy_agrees_with_the_helper_on_every_input(self, content):
        self.assertEqual(
            _provider_entry_content(content),
            _normalize_hash_content(content),
            f"inline provider normalization diverged for {content!r}",
        )

    def test_each_documented_row_agrees_through_the_provider_too(self):
        for label, (raw, expected) in NORMALIZATION.items():
            with self.subTest(label):
                self.assertEqual(_provider_entry_content(raw), expected)

    def test_the_provider_path_really_rewrites_content(self):
        """Premise: agreement is not two pass-throughs agreeing about nothing.

        If the inline branch were never entered the provider would return the
        source bytes verbatim and still match a helper that had also stopped
        working. The observed rewrite is what makes the differential mean
        something.
        """
        produced = _provider_entry_content(b"one\r\ntwo\r\n")
        self.assertEqual(produced, b"one\ntwo\n")
        self.assertNotEqual(produced, b"one\r\ntwo\r\n")

    def test_the_differential_would_report_a_copy_missing_the_nul_gate(self):
        """Premise: the corpus contains an input that separates the two rules."""
        disagreements = {
            label
            for label, (raw, _expected) in NORMALIZATION.items()
            if _without_nul_gate(raw) != _provider_entry_content(raw)
        }
        self.assertEqual(disagreements, {"CRLF inside NUL-bearing content"})

    def test_the_differential_would_report_a_copy_that_folds_repeatedly(self):
        """Premise: and one that separates a single pass from a fixed point."""
        disagreements = {
            label
            for label, (raw, _expected) in NORMALIZATION.items()
            if _until_stable(raw) != _provider_entry_content(raw)
        }
        self.assertEqual(disagreements, {"carriage return before a CRLF pair"})


# ---------------------------------------------------------------------------
# OBL-HASHING-056 - what a slice fingerprint is allowed to depend on
# ---------------------------------------------------------------------------

#: The component alphabet for synthetic slice graphs. Five names is enough for
#: a seed, an unreachable island, a chain and a cycle, and keeps a shrunk
#: counterexample readable.
GRAPH_NAMES = ("alpha", "beta", "gamma", "delta", "epsilon")

#: The component the metamorphic step adds. Never a member of GRAPH_NAMES, so
#: an explicit slice drawn from that alphabet can never already name it.
NEWCOMER = "zeta"


def _member_digest(name: str) -> str:
    """A stand-in component digest. Fixed per name, so a diff means a diff."""
    return hashlib.sha256(name.encode("utf-8")).hexdigest()


def _downstream(graph: Dict[str, dict], seed: str) -> Set[str]:
    """The seed and everything reachable along `consumers`, by hand.

    Deliberately a depth-first walk over a plain list, so that it shares no
    code with the breadth-first `consumer_closure` it is used to check.
    """
    seen = {seed}
    pending = [seed]
    while pending:
        current = pending.pop()
        for consumer in graph.get(current, {}).get("consumers", []):
            if consumer in graph and consumer not in seen:
                seen.add(consumer)
                pending.append(consumer)
    return seen


class _SliceCase(NamedTuple):
    """One graph, one explicit slice, one closure slice, one addition."""

    names: List[str]
    edges: Dict[str, List[str]]
    newcomer_edges: List[str]
    wired_into: Optional[str]
    members: List[str]
    seed: str


@st.composite
def slice_cases(draw) -> _SliceCase:
    names = draw(
        st.lists(st.sampled_from(GRAPH_NAMES), min_size=1, max_size=5, unique=True)
    )
    edges = {
        name: sorted(draw(st.sets(st.sampled_from(names), max_size=3)))
        for name in names
    }
    return _SliceCase(
        names=names,
        edges=edges,
        newcomer_edges=sorted(draw(st.sets(st.sampled_from(names), max_size=2))),
        wired_into=draw(st.one_of(st.none(), st.sampled_from(names))),
        members=draw(
            st.lists(
                st.sampled_from(names), min_size=1, max_size=len(names), unique=True
            )
        ),
        seed=draw(st.sampled_from(names)),
    )


def _graph_of(case: _SliceCase, *, added: bool) -> Dict[str, dict]:
    graph = {name: {"consumers": list(case.edges[name])} for name in case.names}
    if added:
        graph[NEWCOMER] = {"consumers": list(case.newcomer_edges)}
        if case.wired_into is not None:
            graph[case.wired_into] = {
                "consumers": [*case.edges[case.wired_into], NEWCOMER]
            }
    return graph


def _entries_of(case: _SliceCase, *, added: bool) -> Dict[str, dict]:
    names = [*case.names, NEWCOMER] if added else list(case.names)
    return {
        name: {"fingerprints": {"exact": _member_digest(name)}} for name in names
    }


def _slice_entry(
    name: str, definition: dict, case: _SliceCase, *, added: bool
) -> dict:
    return _recompute_slice_entry(
        name,
        definition,
        _entries_of(case, added=added),
        strict=True,
        graph_components=_graph_of(case, added=added),
    )


class SliceFingerprintStabilityTests(unittest.TestCase):
    """OBL-HASHING-056: unrelated additions and reorderings must not move it."""

    @PROFILE
    @given(case=slice_cases())
    def test_an_addition_moves_a_slice_only_by_changing_its_membership(self, case):
        explicit = {"mode": "exact", "components": list(case.members)}
        before = _slice_entry("explicit", explicit, case, added=False)
        after = _slice_entry("explicit", explicit, case, added=True)
        self.assertEqual(canonical_json(before), canonical_json(after))
        self.assertEqual(before["component_digests"], after["component_digests"])

        reversed_members = {"mode": "exact", "components": list(reversed(case.members))}
        reordered = _slice_entry("explicit", reversed_members, case, added=False)
        self.assertEqual(canonical_json(before), canonical_json(reordered))

        closure = {"mode": "exact", "closure_of": case.seed}
        closed_before = _slice_entry("closure", closure, case, added=False)
        closed_after = _slice_entry("closure", closure, case, added=True)
        oracle_before = _downstream(_graph_of(case, added=False), case.seed)
        oracle_after = _downstream(_graph_of(case, added=True), case.seed)
        self.assertEqual(closed_before["components"], sorted(oracle_before))
        self.assertEqual(closed_after["components"], sorted(oracle_after))

        moved = closed_before["fingerprint"] != closed_after["fingerprint"]
        self.assertEqual(moved, oracle_before != oracle_after)
        self.assertEqual(moved, NEWCOMER in oracle_after)
        if case.wired_into is None:
            self.assertEqual(
                canonical_json(closed_before), canonical_json(closed_after)
            )

    def test_the_comparison_notices_a_member_digest_that_actually_moved(self):
        """Premise: the canonical_json equality above is not vacuously true."""
        case = _SliceCase(
            names=["alpha", "beta"],
            edges={"alpha": ["beta"], "beta": []},
            newcomer_edges=[],
            wired_into=None,
            members=["alpha", "beta"],
            seed="alpha",
        )
        explicit = {"mode": "exact", "components": ["alpha", "beta"]}
        before = _slice_entry("explicit", explicit, case, added=False)
        entries = _entries_of(case, added=False)
        entries["beta"]["fingerprints"]["exact"] = _member_digest("beta-moved")
        after = _recompute_slice_entry(
            "explicit",
            explicit,
            entries,
            strict=True,
            graph_components=_graph_of(case, added=False),
        )
        self.assertNotEqual(before["fingerprint"], after["fingerprint"])
        self.assertNotEqual(canonical_json(before), canonical_json(after))

    def test_the_closure_oracle_reports_a_wiring_that_actually_reaches(self):
        """Premise: at least one drawn shape does make the newcomer reachable."""
        case = _SliceCase(
            names=["alpha", "beta"],
            edges={"alpha": ["beta"], "beta": []},
            newcomer_edges=[],
            wired_into="beta",
            members=["alpha"],
            seed="alpha",
        )
        self.assertNotIn(NEWCOMER, _downstream(_graph_of(case, added=False), "alpha"))
        self.assertIn(NEWCOMER, _downstream(_graph_of(case, added=True), "alpha"))


def _stability_repository() -> Scenario:
    """Three components, one consumers edge, one explicit and one closure slice."""
    scene = Scenario()
    scene.component(
        "core", path="core", provider="path-hash", boundary=["api.txt"],
        consumers=["web"],
    )
    scene.component("web", path="web", provider="path-hash", boundary=["api.txt"])
    scene.component("cli", path="cli", provider="path-hash", boundary=["api.txt"])
    for name in ("core", "web", "cli"):
        scene.file(f"{name}/api.txt", f"{name}\n")
        scene.file(f"{name}/impl.txt", f"{name} implementation\n")
    scene.slice("pair", mode="exact", components=["core", "cli"])
    scene.slice("downstream", mode="exact", closure_of="core")
    scene.commit()
    return scene


class RepositorySliceStabilityTests(unittest.TestCase):
    """OBL-HASHING-056, again through `generate` rather than the helper."""

    def _slices(self, scene: Scenario) -> Dict[str, dict]:
        return scene.generate()["slices"]

    def test_adding_an_unrelated_component_leaves_both_slices_byte_identical(self):
        with _stability_repository() as scene:
            before = self._slices(scene)
            scene.component(
                "docs", path="docs", provider="path-hash", boundary=["api.txt"]
            )
            scene.file("docs/api.txt", "docs\n")
            scene.commit("add an unrelated component")
            after = self._slices(scene)
            for name in ("pair", "downstream"):
                with self.subTest(name):
                    self.assertEqual(
                        canonical_json(before[name]), canonical_json(after[name])
                    )
                    self.assertEqual(
                        before[name]["component_digests"],
                        after[name]["component_digests"],
                    )

    def test_a_closure_slice_moves_when_the_newcomer_becomes_reachable(self):
        """Premise for the test above: the closure fingerprint can move at all."""
        with _stability_repository() as scene:
            before = self._slices(scene)["downstream"]
            self.assertEqual(before["components"], ["core", "web"])
            scene.component(
                "docs", path="docs", provider="path-hash", boundary=["api.txt"]
            )
            scene.file("docs/api.txt", "docs\n")
            scene.config["components"]["web"]["consumers"] = ["docs"]
            scene.commit("wire the newcomer downstream of web")
            after = self._slices(scene)["downstream"]
            self.assertEqual(after["components"], ["core", "docs", "web"])
            self.assertNotEqual(before["fingerprint"], after["fingerprint"])
            self.assertIn("docs", after["component_digests"])

    def test_reversing_an_explicit_member_list_changes_nothing(self):
        with _stability_repository() as scene:
            before = self._slices(scene)["pair"]
            self.assertEqual(scene.config["slices"]["pair"]["components"], ["core", "cli"])
            scene.config["slices"]["pair"]["components"] = ["cli", "core"]
            scene.commit("reverse the member list")
            after = self._slices(scene)["pair"]
            self.assertEqual(canonical_json(before), canonical_json(after))

    def test_reordering_the_config_keys_changes_no_slice_fingerprint(self):
        with _stability_repository() as scene:
            before = self._slices(scene)
            scene.config["components"] = dict(
                reversed(list(scene.config["components"].items()))
            )
            scene.config["slices"] = dict(
                reversed(list(scene.config["slices"].items()))
            )
            scene.config = dict(reversed(list(scene.config.items())))
            scene.commit("reorder every config mapping")
            after = self._slices(scene)
            self.assertEqual(set(before), set(after))
            for name in before:
                with self.subTest(name):
                    self.assertEqual(
                        canonical_json(before[name]), canonical_json(after[name])
                    )


# ---------------------------------------------------------------------------
# OBL-HASHING-100 - every entry point that can write a lock
# ---------------------------------------------------------------------------

LOCK_NAME = "boundary.lock.json"

#: The slice membership a valid run declares, and the typo'd one that must be
#: refused. "ghost" is not a declared component.
VALID_MEMBERS = ("svc", "web")
TYPO_MEMBERS = ("svc", "web", "ghost")

#: The exact refusal observed from every entry point.
UNKNOWN_MEMBER_MESSAGE = "Slice 'agg' references unknown component: ghost"

_PACKAGE = Path(boundver.__file__).resolve().parent


class _Outcome(NamedTuple):
    """What one lock-writing entry point did with one config."""

    refused: bool
    message: str
    wrote: bool


def _lock_bytes(scene: Scenario) -> bytes:
    path = scene.root / LOCK_NAME
    return path.read_bytes() if path.exists() else b""


def _slice_repository(members: Sequence[str]) -> Scenario:
    scene = Scenario()
    scene.component("svc", path="svc", provider="path-hash", boundary=["api.txt"])
    scene.component("web", path="web", provider="path-hash", boundary=["api.txt"])
    scene.file("svc/api.txt", "one\n")
    scene.file("web/api.txt", "one\n")
    scene.slice("agg", mode="exact", components=list(members))
    scene.commit()
    return scene


def _committed_lock_then_drift(scene: Scenario, members: Sequence[str]) -> None:
    """Record a lock in HEAD, then drift content and set the slice membership.

    Both `generate --components` and `verify --update` refuse to write without
    an existing lock in the selected source, and `verify --update` writes only
    when it has something to repair, so the premise runs need both steps.
    """
    run_cli(scene.root, "generate")
    scene.git("add", "--all")
    scene.git("commit", "-m", "record the lock")
    scene.file("svc/api.txt", "two\n")
    scene.config["slices"]["agg"]["components"] = list(members)
    scene.commit("drift and re-declare the slice")


def _drive_generate(members: Sequence[str]) -> _Outcome:
    with _slice_repository(members) as scene:
        before = _lock_bytes(scene)
        result = run_cli(scene.root, "generate")
        return _Outcome(
            result.returncode != 0, result.stderr, _lock_bytes(scene) != before
        )


def _drive_generate_components(members: Sequence[str]) -> _Outcome:
    with _slice_repository(VALID_MEMBERS) as scene:
        _committed_lock_then_drift(scene, members)
        before = _lock_bytes(scene)
        result = run_cli(scene.root, "generate", "--components", "svc")
        return _Outcome(
            result.returncode != 0, result.stderr, _lock_bytes(scene) != before
        )


def _drive_verify_update(members: Sequence[str]) -> _Outcome:
    with _slice_repository(VALID_MEMBERS) as scene:
        _committed_lock_then_drift(scene, members)
        before = _lock_bytes(scene)
        result = run_cli(scene.root, "verify", "--update")
        return _Outcome(
            result.returncode != 0, result.stderr, _lock_bytes(scene) != before
        )


def _drive_public_generate(members: Sequence[str]) -> _Outcome:
    with _slice_repository(members) as scene:
        before = _lock_bytes(scene)
        previous = Path.cwd()
        try:
            os.chdir(scene.root)
            try:
                boundver.generate()
            except ConfigError as exc:
                return _Outcome(True, str(exc), _lock_bytes(scene) != before)
            return _Outcome(False, "", _lock_bytes(scene) != before)
        finally:
            os.chdir(previous)


#: How to reach each lock-writing function found in the source. The keys are
#: derived at runtime by `_lock_writing_functions`; a function that starts
#: writing a lock and is not listed here fails the first test below.
LOCK_WRITERS: Dict[str, Tuple[str, ...]] = {
    "core.py::_cmd_generate": ("generate", "generate --components"),
    "core.py::_cmd_verify": ("verify --update",),
    "__init__.py::generate": ("boundver.generate",),
}

#: One runnable driver per spelling named above.
DRIVERS = {
    "generate": _drive_generate,
    "generate --components": _drive_generate_components,
    "verify --update": _drive_verify_update,
    "boundver.generate": _drive_public_generate,
}


def _writers_in_source(label: str, source: str) -> Set[str]:
    """Functions in *source* that call the lock writer, by `label::name`."""
    found: Set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for inner in ast.walk(node):
            if not isinstance(inner, ast.Call):
                continue
            called = inner.func
            name = (
                called.id
                if isinstance(called, ast.Name)
                else called.attr if isinstance(called, ast.Attribute) else None
            )
            if name == "_write_lockfile_atomic":
                found.add(f"{label}::{node.name}")
                break
    return found


def _lock_writing_functions() -> Set[str]:
    """Every function in the shipped package that writes a lockfile."""
    found: Set[str] = set()
    for module in sorted(_PACKAGE.glob("*.py")):
        found |= _writers_in_source(
            module.name, module.read_text(encoding="utf-8")
        )
    return found


class UnknownSliceMemberTests(unittest.TestCase):
    """OBL-HASHING-100: the typo must be refused before anything is written."""

    def test_the_source_walk_finds_a_call_it_is_shown(self):
        """Premise: an empty enumeration would make every check below vacuous."""
        synthetic = (
            "def outer():\n"
            "    def helper():\n"
            "        pass\n"
            "    _write_lockfile_atomic(path, value)\n"
            "\n"
            "def bystander():\n"
            "    return core._write_lockfile_atomic(path, value)\n"
            "\n"
            "def uninvolved():\n"
            "    return 1\n"
        )
        self.assertEqual(
            _writers_in_source("fake.py", synthetic),
            {"fake.py::outer", "fake.py::bystander"},
        )

    def test_the_driver_table_covers_every_function_that_writes_a_lock(self):
        discovered = _lock_writing_functions()
        self.assertTrue(discovered, "no lock-writing function was found at all")
        self.assertEqual(discovered, set(LOCK_WRITERS))
        named = {name for names in LOCK_WRITERS.values() for name in names}
        self.assertEqual(named, set(DRIVERS))

    def test_every_lock_writing_entry_point_writes_for_a_valid_config(self):
        """Premise: each driver reaches the write, so 'did not write' can mean it."""
        for name, drive in DRIVERS.items():
            with self.subTest(name):
                outcome = drive(VALID_MEMBERS)
                self.assertFalse(outcome.refused, outcome.message)
                self.assertTrue(outcome.wrote, f"{name} wrote no lockfile")

    def test_every_lock_writing_entry_point_refuses_an_unknown_slice_member(self):
        for name, drive in DRIVERS.items():
            with self.subTest(name):
                outcome = drive(TYPO_MEMBERS)
                self.assertTrue(outcome.refused, f"{name} accepted the config")
                self.assertIn(UNKNOWN_MEMBER_MESSAGE, outcome.message)
                self.assertFalse(outcome.wrote, f"{name} wrote a lockfile anyway")


class NullMemberDigestTests(unittest.TestCase):
    """OBL-HASHING-100: strict generation refuses an unknown slice member."""

    def _generated(self, strict: bool) -> Tuple[dict, str]:
        with _slice_repository(TYPO_MEMBERS) as scene:
            lockfile = generate_lockfile(
                scene.config, scene.root, source="head", strict=strict
            )
            return (
                lockfile["slices"]["agg"],
                lockfile["components"]["svc"]["fingerprints"]["exact"],
            )

    def test_a_direct_strict_generate_refuses_to_hash_a_null_member(self):
        """The low-level API fails closed even without config validation."""
        with self.assertRaises(ConfigError):
            self._generated(strict=True)

    def test_lenient_generate_can_publish_an_explicit_null_digest(self):
        """Lenient generation retains its deliberate partial-lock behavior."""
        entry, svc_digest = self._generated(strict=False)
        self.assertEqual(entry["components"], ["ghost", "svc", "web"])
        self.assertIsNone(entry["component_digests"]["ghost"])
        self.assertEqual(entry["component_digests"]["svc"], svc_digest)
        self.assertEqual(set(entry["component_digests"]), {"ghost", "svc", "web"})

    def test_the_lenient_fingerprint_hashes_the_null_member_verbatim(self):
        """A partial member remains an explicit input, not a dropped key."""
        entry, _svc_digest = self._generated(strict=False)
        self.assertEqual(
            entry["fingerprint"],
            sha256_hex(
                canonical_json(
                    {
                        "mode": entry["mode"],
                        "component_digests": entry["component_digests"],
                    }
                )
            ),
        )
        without_ghost = {
            name: digest
            for name, digest in entry["component_digests"].items()
            if name != "ghost"
        }
        self.assertNotEqual(
            entry["fingerprint"],
            sha256_hex(
                canonical_json(
                    {"mode": entry["mode"], "component_digests": without_ghost}
                )
            ),
        )

    def test_strict_and_lenient_generation_diverge_at_the_unknown_member(self):
        with self.assertRaises(ConfigError):
            self._generated(strict=True)
        lenient_entry, _ = self._generated(strict=False)
        self.assertIsNone(lenient_entry["component_digests"]["ghost"])


# ---------------------------------------------------------------------------
# OBL-HASHING-063 - when slice availability is actually required
# ---------------------------------------------------------------------------

#: (api.verify_facets, leaf.verify_facets, defaults.verify_facets) against the
#: slice-scoped issues observed for a `boundary` slice whose `leaf` member
#: publishes no boundary digest. Row three is the premise: an explicit list on
#: an unrelated member is enough to arm `slice_availability_is_required`, so
#: the silence in rows one and five is attributable to the slice-mode conjunct
#: beside it and to nothing else.
AVAILABILITY_ROWS: Dict[str, Tuple[Optional[List[str]], Optional[List[str]], Optional[List[str]], List[str]]] = {
    "gated member list excludes the slice mode": (["exact"], None, None, []),
    "gated member list includes the slice mode": (
        ["boundary"], None, None,
        ["UNAVAILABLE FACET agg.boundary: slice members lack locked or "
         "current digests: leaf"],
    ),
    "an unrelated member carries the explicit list": (
        None, ["exact"], None,
        ["UNAVAILABLE FACET agg.boundary: slice members lack locked or "
         "current digests: leaf"],
    ),
    "no facet policy anywhere": (None, None, None, []),
    "explicit defaults exclude the slice mode": (None, None, ["exact"], []),
    "explicit defaults include the slice mode": (
        None, None, ["boundary"],
        ["UNAVAILABLE FACET agg.boundary: slice members lack locked or "
         "current digests: leaf"],
    ),
}


def _availability_repository(
    api_facets: Optional[List[str]],
    leaf_facets: Optional[List[str]],
    default_facets: Optional[List[str]],
    *,
    members: Sequence[str] = ("api", "leaf"),
) -> Scenario:
    """A boundary slice over one component that has a boundary and one that cannot.

    `leaf` publishes no boundary digest by declaration, which is why the slice
    can hold a null member digest without any computation having failed.
    """
    scene = Scenario()
    scene.component(
        "api", path="api", provider="path-hash", boundary=["contract.txt"],
        verify_facets=api_facets,
    )
    scene.component("leaf", path="leaf", provider="leaf", verify_facets=leaf_facets)
    scene.file("api/contract.txt", "one\n")
    scene.file("leaf/main.py", "x = 1\n")
    if default_facets is not None:
        scene.defaults(verify_facets=default_facets)
    scene.slice("agg", mode="boundary", components=list(members))
    scene.commit()
    return scene


def _slice_issues(issues: Sequence[str]) -> List[str]:
    """Only the diagnostics that name the slice, not its members."""
    return [issue for issue in issues if " agg." in issue]


class SliceAvailabilityGateTests(unittest.TestCase):
    """OBL-HASHING-063: an explicit list alone must not make availability mandatory."""

    def test_the_gate_fires_exactly_where_the_slice_mode_is_gated(self):
        for label, row in AVAILABILITY_ROWS.items():
            api_facets, leaf_facets, default_facets, expected = row
            with self.subTest(label):
                with _availability_repository(
                    api_facets, leaf_facets, default_facets
                ) as scene:
                    lockfile = scene.generate(strict=False)
                    observations: List[str] = []
                    issues = scene.verify(lockfile, observations=observations)
                    self.assertEqual(_slice_issues(issues), expected)

    def test_the_member_digest_really_is_null_in_every_row(self):
        """Premise: without a null member the gate could never fire at all."""
        for label, row in AVAILABILITY_ROWS.items():
            api_facets, leaf_facets, default_facets, _expected = row
            with self.subTest(label):
                with _availability_repository(
                    api_facets, leaf_facets, default_facets
                ) as scene:
                    digests = scene.generate(strict=False)["slices"]["agg"][
                        "component_digests"
                    ]
                    self.assertIsNone(digests["leaf"])
                    self.assertIsNotNone(digests["api"])

    def test_an_explicit_facets_override_requires_availability_regardless(self):
        """The contrast case: `--facets` arms availability without any config."""
        with _availability_repository(None, None, None) as scene:
            lockfile = scene.generate(strict=False)
            issues = scene.verify(lockfile, facets=["boundary"])
            self.assertIn(
                "UNAVAILABLE FACET agg.boundary: slice members lack locked or "
                "current digests: leaf",
                issues,
            )


# ---------------------------------------------------------------------------
# OBL-HASHING-104 - one diagnostic per slice, and the right one
# ---------------------------------------------------------------------------


def _drifted(scene: Scenario) -> Tuple[dict, dict, List[str], List[str]]:
    """Lock the slice, move a member's boundary content, then verify."""
    lockfile = scene.generate(strict=False)
    locked_slice = lockfile["slices"]["agg"]
    scene.file("api/contract.txt", "two\n")
    scene.commit("move the boundary content")
    current_slice = scene.generate(strict=False)["slices"]["agg"]
    observations: List[str] = []
    issues = scene.verify(lockfile, observations=observations)
    return locked_slice, current_slice, issues, observations


class SliceDiagnosticExclusivityTests(unittest.TestCase):
    """OBL-HASHING-104: never both messages, and never neither when it matters."""

    def test_an_unavailable_slice_does_not_also_report_a_mismatch(self):
        with _availability_repository(["boundary"], None, None) as scene:
            locked, current, issues, observations = _drifted(scene)
            # Premise inside the test: the mismatch condition genuinely holds,
            # so the missing SLICE MISMATCH is suppression and not absence.
            self.assertNotEqual(locked, current)
            self.assertNotEqual(locked["fingerprint"], current["fingerprint"])
            self.assertEqual(
                _slice_issues(issues),
                ["UNAVAILABLE FACET agg.boundary: slice members lack locked or "
                 "current digests: leaf"],
            )
            self.assertEqual(_slice_issues(observations), [])

    def test_the_same_drift_reports_a_mismatch_without_the_null_member(self):
        """Premise: the mismatch branch is reachable with exactly this drift."""
        with _availability_repository(
            ["boundary"], None, None, members=("api",)
        ) as scene:
            locked, current, issues, _observations = _drifted(scene)
            self.assertNotEqual(locked["fingerprint"], current["fingerprint"])
            slice_issues = _slice_issues(issues)
            self.assertEqual(len(slice_issues), 1, slice_issues)
            self.assertTrue(
                slice_issues[0].startswith("SLICE MISMATCH agg.boundary: "),
                slice_issues[0],
            )
            self.assertNotIn("UNAVAILABLE FACET", slice_issues[0])

    def test_a_null_member_that_is_not_required_still_reports_the_mismatch(self):
        """The converse clause: tolerating the null must not hide real drift."""
        with _availability_repository(None, None, None) as scene:
            locked, current, issues, _observations = _drifted(scene)
            self.assertIsNone(locked["component_digests"]["leaf"])
            self.assertNotEqual(locked["fingerprint"], current["fingerprint"])
            slice_issues = _slice_issues(issues)
            self.assertEqual(len(slice_issues), 1, slice_issues)
            self.assertTrue(
                slice_issues[0].startswith("SLICE MISMATCH agg.boundary: "),
                slice_issues[0],
            )


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
