#!/usr/bin/env python3
"""Generate the public CLI reference from the live argparse parser.

Usage:
    python -I scripts/generate_cli_reference.py
    python -I scripts/generate_cli_reference.py --check
"""

from __future__ import annotations

import argparse
import os
import sys
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, Sequence


ROOT = Path(__file__).resolve().parents[1]
SURFACE = ROOT / "docs" / "cli-reference.md"
sys.path.insert(0, str(ROOT / "src"))

from boundver._cli_parser import build_parser  # noqa: E402


@contextmanager
def _stable_help_width() -> Iterator[None]:
    """Keep argparse wrapping independent of the caller's terminal width."""
    previous = os.environ.get("COLUMNS")
    os.environ["COLUMNS"] = "100"
    try:
        yield
    finally:
        if previous is None:
            os.environ.pop("COLUMNS", None)
        else:
            os.environ["COLUMNS"] = previous


def _markdown_cell(value: object) -> str:
    if value is None:
        return "—"
    text = str(value).replace("|", "\\|")
    return " ".join(text.splitlines()).strip() or "—"


def _code(value: object) -> str:
    text = _markdown_cell(value).replace("`", "\\`")
    return f"`{text}`"


def _argument_name(action: argparse.Action) -> str:
    if action.option_strings:
        return ", ".join(_code(option) for option in action.option_strings)
    return _code(action.metavar or action.dest)


def _argument_value(action: argparse.Action) -> str:
    if action.nargs == 0:
        return "—"
    if action.choices is not None:
        value = "{" + ",".join(str(choice) for choice in action.choices) + "}"
    else:
        value = str(action.metavar or action.dest.upper())
    if action.nargs in {"?", "*", "+"}:
        value += str(action.nargs)
    elif isinstance(action.nargs, int) and action.nargs != 1:
        value += f" × {action.nargs}"
    return _code(value)


def _argument_default(action: argparse.Action) -> str:
    if action.required:
        return "required"
    value = action.default
    if value is None or value is argparse.SUPPRESS:
        return "—"
    if value == "":
        return "empty"
    if value == []:
        return "none"
    if isinstance(value, bool):
        return _code(str(value).lower())
    return _code(value)


def _render_text(out: list[str], value: str | None) -> None:
    if not value:
        return
    for block in value.strip().split("\n\n"):
        lines = block.splitlines()
        if len(lines) > 1 and any(line.startswith("  ") for line in lines[1:]):
            out.extend(["```text", *lines, "```", ""])
        else:
            out.extend([" ".join(line.strip() for line in lines), ""])


def _render_arguments(out: list[str], parser: argparse.ArgumentParser) -> None:
    actions = [
        action
        for action in parser._actions
        if not isinstance(action, argparse._SubParsersAction)
    ]
    if not actions:
        return
    out.extend(
        [
            "| Argument | Value | Default | Description |",
            "| --- | --- | --- | --- |",
        ]
    )
    for action in actions:
        out.append(
            "| "
            + " | ".join(
                (
                    _argument_name(action),
                    _argument_value(action),
                    _argument_default(action),
                    _markdown_cell(action.help),
                )
            )
            + " |"
        )
    out.append("")


def _format_usage(parser: argparse.ArgumentParser) -> list[str]:
    """Return usage lines whose wrapping is stable across Python releases."""
    lines: list[str] = []
    for line in parser.format_usage().strip().splitlines():
        if line.strip() == "..." and lines:
            lines[-1] += " ..."
        else:
            lines.append(line.rstrip())
    return lines


def _subcommands(
    parser: argparse.ArgumentParser,
) -> tuple[argparse._SubParsersAction, list[tuple[str, str, argparse.ArgumentParser]]]:
    action = next(
        action
        for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    )
    summaries = {choice.dest: choice.help for choice in action._choices_actions}
    commands = [
        (name, summaries.get(name, ""), command_parser)
        for name, command_parser in action.choices.items()
    ]
    return action, commands


def render() -> str:
    """Return deterministic Markdown for the current public parser."""
    with _stable_help_width():
        parser = build_parser(version="VERSION", epilog="")
        _action, commands = _subcommands(parser)
        out = [
            "<!-- Generated by scripts/generate_cli_reference.py. Do not edit. -->",
            "<!-- Edit src/boundver/_cli_parser.py and regenerate. -->",
            "",
            "# CLI reference",
            "",
            "This page is generated from the parser shipped by Boundver. For workflow rules,",
            "configuration examples, and exit-code semantics, use the",
            "[behavioral reference](reference.md).",
            "",
            "## Command index",
            "",
            "| Command | Purpose |",
            "| --- | --- |",
        ]
        for name, summary, _command_parser in commands:
            out.append(f"| [`boundver {name}`](#{name}) | {_markdown_cell(summary)} |")
        out.extend(["", "## Global syntax", "", "```text"])
        out.extend(_format_usage(parser))
        out.extend(["```", ""])
        _render_text(out, parser.description)
        _render_arguments(out, parser)

        for name, _summary, command_parser in commands:
            out.extend([f'<a id="{name}"></a>', "", f"## `boundver {name}`", ""])
            out.extend(["```text", *_format_usage(command_parser), "```", ""])
            _render_text(out, command_parser.description)
            _render_arguments(out, command_parser)
            _render_text(out, command_parser.epilog)

    return "\n".join(out).rstrip() + "\n"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when docs/cli-reference.md is not current",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    expected = render()
    if args.check:
        try:
            current = SURFACE.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"cannot read {SURFACE}: {exc}", file=sys.stderr)
            return 2
        if current != expected:
            print(
                "docs/cli-reference.md is stale; run "
                "python -I scripts/generate_cli_reference.py",
                file=sys.stderr,
            )
            return 1
        print("CLI reference is current.")
        return 0

    try:
        SURFACE.write_text(expected, encoding="utf-8", newline="\n")
    except OSError as exc:
        print(f"cannot write {SURFACE}: {exc}", file=sys.stderr)
        return 2
    print(f"Rendered {SURFACE.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
