#!/usr/bin/env python3
"""Generate and verify hash-locked automation requirements.

The checked-in TOML manifest is the reviewed version policy. ``generate``
copies SHA-256 digests for every non-yanked wheel in each pinned PyPI release
into local lock files. ``verify`` is network-free and proves structural and
cross-file consistency. ``check`` additionally compares generated bytes with
current official PyPI JSON metadata without changing the worktree.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

try:
    import tomllib
except ImportError:  # pragma: no cover - exercised by the Python 3.9 CI job
    import tomli as tomllib


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "scripts" / "release-tool-lock.toml"
ARTIFACTS = ROOT / "scripts" / "release-tool-artifacts.json"
NAME_RE = re.compile(r"[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?")
VERSION_RE = re.compile(r"[A-Za-z0-9](?:[A-Za-z0-9.!+_-]*[A-Za-z0-9])?")
HASH_RE = re.compile(r"[0-9a-f]{64}")
REQUIREMENT_RE = re.compile(
    r"(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)==(?P<version>[^;\s]+)"
    r"(?:;\s*(?P<marker>.+))?"
)
ALLOWED_MARKERS = {
    "python_version < '3.10'",
    "python_version < '3.11'",
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
}
READ_CHUNK_BYTES = 64 * 1024
MAX_MANIFEST_BYTES = 1024 * 1024
MAX_ARTIFACT_EVIDENCE_BYTES = 8 * 1024 * 1024
MAX_LOCK_FILE_BYTES = 4 * 1024 * 1024
MAX_PYPI_METADATA_BYTES = 8 * 1024 * 1024
MAX_PYPI_FILES = 4096
MAX_WHEEL_FILENAME_BYTES = 1024
MAX_REQUIREMENTS = 256
MAX_TOTAL_WHEELS = 20_000
MAX_JSON_INTEGER_DIGITS = 4300
MAX_TOML_INTEGER_DIGITS = 640


class LockError(RuntimeError):
    """The lock policy or generated files are invalid."""


def _bounded_json_int(value: str) -> int:
    """Parse a JSON integer independently of Python's mutable digit limit."""
    if re.fullmatch(r"-?(?:0|[1-9][0-9]*)", value) is None:
        raise ValueError("invalid JSON integer")
    negative = value.startswith("-")
    digits = value[1:] if negative else value
    if len(digits) > MAX_JSON_INTEGER_DIGITS:
        raise ValueError(
            "JSON integer exceeds the "
            f"{MAX_JSON_INTEGER_DIGITS}-decimal-digit limit"
        )
    result = 0
    for offset in range(0, len(digits), 9):
        chunk = digits[offset : offset + 9]
        result = result * (10 ** len(chunk)) + int(chunk)
    return -result if negative else result


def _bounded_json_float(value: str) -> float:
    result = float(value)
    if not math.isfinite(result):
        raise ValueError("non-finite JSON number is not supported")
    return result


def _reject_json_constant(_value: str) -> Any:
    raise ValueError("non-finite JSON constant is not supported")


def _unique_json_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key is not supported")
        result[key] = value
    return result


def _strict_json_loads(document: str) -> Any:
    return json.loads(
        document,
        object_pairs_hook=_unique_json_object,
        parse_constant=_reject_json_constant,
        parse_float=_bounded_json_float,
        parse_int=_bounded_json_int,
    )


def _toml_has_oversized_numeric_token(text: str) -> bool:
    """Find oversized TOML value tokens without examining strings or keys."""
    index = 0
    state = "normal"
    root_in_value = False
    table_header_depth = 0
    at_statement_start = True
    array_frame = 0
    inline_key_frame = 1
    inline_value_frame = 2
    containers = bytearray()

    def in_key_context() -> bool:
        if table_header_depth:
            return True
        if containers:
            return containers[-1] == inline_key_frame
        return not root_in_value

    def reset_line() -> None:
        nonlocal root_in_value, table_header_depth, at_statement_start
        if not containers:
            root_in_value = False
            table_header_depth = 0
            at_statement_start = True

    while index < len(text):
        char = text[index]
        if state == "comment":
            if char in "\r\n":
                state = "normal"
                reset_line()
            index += 1
            continue
        if state in {"basic", "multiline-basic"}:
            if char == "\\":
                index += 2
                continue
            if state == "basic" and char == '"':
                state = "normal"
                index += 1
                continue
            if state == "multiline-basic" and char == '"':
                end = index
                while end < len(text) and text[end] == '"':
                    end += 1
                if end - index >= 3:
                    state = "normal"
                index = end
                continue
            index += 1
            continue
        if state in {"literal", "multiline-literal"}:
            if state == "literal" and char == "'":
                state = "normal"
                index += 1
                continue
            if state == "multiline-literal" and char == "'":
                end = index
                while end < len(text) and text[end] == "'":
                    end += 1
                if end - index >= 3:
                    state = "normal"
                index = end
                continue
            index += 1
            continue

        if char == "#":
            state = "comment"
            index += 1
            continue
        if char in "\r\n":
            reset_line()
            index += 1
            continue
        if char in " \t":
            index += 1
            continue
        if text.startswith('\"\"\"', index):
            state = "multiline-basic"
            at_statement_start = False
            index += 3
            continue
        if text.startswith("'''", index):
            state = "multiline-literal"
            at_statement_start = False
            index += 3
            continue
        if char == '"':
            state = "basic"
            at_statement_start = False
            index += 1
            continue
        if char == "'":
            state = "literal"
            at_statement_start = False
            index += 1
            continue
        if char == "[":
            if table_header_depth:
                table_header_depth += 1
            elif not containers and not root_in_value and at_statement_start:
                table_header_depth = 1
            else:
                containers.append(array_frame)
            at_statement_start = False
            index += 1
            continue
        if char == "]":
            if table_header_depth:
                table_header_depth -= 1
            elif containers and containers[-1] == array_frame:
                containers.pop()
            at_statement_start = False
            index += 1
            continue
        if char == "{":
            containers.append(inline_key_frame)
            at_statement_start = False
            index += 1
            continue
        if char == "}":
            if containers and containers[-1] in {
                inline_key_frame,
                inline_value_frame,
            }:
                containers.pop()
            at_statement_start = False
            index += 1
            continue
        if char == "=":
            if containers and containers[-1] == inline_key_frame:
                containers[-1] = inline_value_frame
            elif not containers and not table_header_depth:
                root_in_value = True
            at_statement_start = False
            index += 1
            continue
        if char == ",":
            if containers and containers[-1] == inline_value_frame:
                containers[-1] = inline_key_frame
            at_statement_start = False
            index += 1
            continue
        if (
            not in_key_context()
            and char == "0"
            and index + 1 < len(text)
            and text[index + 1] in "bBoOxX"
        ):
            prefix = text[index + 1].lower()
            valid_digits = {
                "b": "01",
                "o": "01234567",
                "x": "0123456789abcdefABCDEF",
            }[prefix]
            index += 2
            digits = 0
            while index < len(text) and (
                text[index] in valid_digits or text[index] == "_"
            ):
                if text[index] != "_":
                    digits += 1
                    if digits > MAX_TOML_INTEGER_DIGITS:
                        return True
                index += 1
            continue
        if not in_key_context() and "0" <= char <= "9":
            digits = 0
            while index < len(text) and (
                "0" <= text[index] <= "9" or text[index] == "_"
            ):
                if text[index] != "_":
                    digits += 1
                    if digits > MAX_TOML_INTEGER_DIGITS:
                        return True
                index += 1
            continue
        at_statement_start = False
        index += 1
    return False


def _strict_toml_loads(document: str) -> dict[str, Any]:
    if _toml_has_oversized_numeric_token(document):
        raise ValueError(
            "TOML numeric token exceeds the "
            f"{MAX_TOML_INTEGER_DIGITS}-digit cross-runtime safety limit"
        )
    return tomllib.loads(document)


@dataclass(frozen=True)
class Requirement:
    name: str
    version: str
    marker: str | None = None

    @property
    def canonical_name(self) -> str:
        return re.sub(r"[-_.]+", "-", self.name).lower()

    @property
    def rendered(self) -> str:
        base = f"{self.name}=={self.version}"
        return f"{base}; {self.marker}" if self.marker else base


@dataclass(frozen=True)
class Profile:
    name: str
    lock: Path
    includes: tuple[str, ...]
    requirements: tuple[Requirement, ...]


def _read_file_bounded(path: Path, max_bytes: int, label: str) -> bytes:
    try:
        advertised_size = path.stat().st_size
        if advertised_size > max_bytes:
            raise LockError(f"{label} exceeds the {max_bytes}-byte limit: {path}")
        chunks: list[bytes] = []
        total = 0
        with path.open("rb") as stream:
            while total < max_bytes:
                requested = min(READ_CHUNK_BYTES, max_bytes - total)
                chunk = stream.read(requested)
                if len(chunk) > requested:
                    raise LockError(
                        f"{label} exceeded a bounded read request: {path}"
                    )
                if not chunk:
                    break
                chunks.append(chunk)
                total += len(chunk)
            if stream.read(1):
                raise LockError(f"{label} exceeds the {max_bytes}-byte limit: {path}")
    except LockError:
        raise
    except OSError as error:
        raise LockError(f"cannot read {label}: {error}") from error
    if total != advertised_size:
        raise LockError(f"{label} changed while being read: {path}")
    return b"".join(chunks)


def _file_matches(
    path: Path,
    expected: bytes,
    max_bytes: int,
    label: str,
    *,
    missing_is_mismatch: bool = False,
) -> bool:
    if len(expected) > max_bytes:
        raise LockError(f"generated {label} exceeds the {max_bytes}-byte limit")
    try:
        advertised_size = path.stat().st_size
        if advertised_size > max_bytes:
            raise LockError(f"{label} exceeds the {max_bytes}-byte limit: {path}")
        if advertised_size != len(expected):
            return False
        expected_view = memoryview(expected)
        offset = 0
        with path.open("rb") as stream:
            while offset < len(expected):
                requested = min(READ_CHUNK_BYTES, len(expected) - offset)
                chunk = stream.read(requested)
                if len(chunk) > requested:
                    raise LockError(
                        f"{label} exceeded a bounded read request: {path}"
                    )
                if not chunk or chunk != expected_view[offset : offset + len(chunk)]:
                    return False
                offset += len(chunk)
            return not stream.read(1)
    except FileNotFoundError:
        if missing_is_mismatch:
            return False
        raise LockError(f"cannot read {label}: file does not exist: {path}") from None
    except LockError:
        raise
    except OSError as error:
        if missing_is_mismatch:
            return False
        raise LockError(f"cannot read {label}: {error}") from error


def _require_mapping(value: object, context: str) -> Mapping[str, Any]:
    if not isinstance(value, dict):
        raise LockError(f"{context} must be a table")
    return value


def _require_string(value: object, context: str) -> str:
    if not isinstance(value, str) or not value:
        raise LockError(f"{context} must be a non-empty string")
    return value


def _wheel_filename_within_limit(value: str) -> bool:
    try:
        return len(value.encode("utf-8")) <= MAX_WHEEL_FILENAME_BYTES
    except UnicodeEncodeError:
        return False


def _parse_requirement(raw: object, context: str) -> Requirement:
    text = _require_string(raw, context)
    match = REQUIREMENT_RE.fullmatch(text)
    if match is None:
        raise LockError(f"{context} must be an exact name==version requirement")
    name = match.group("name")
    version = match.group("version")
    marker = match.group("marker")
    if NAME_RE.fullmatch(name) is None or VERSION_RE.fullmatch(version) is None:
        raise LockError(f"{context} contains an invalid name or version")
    if marker is not None and marker not in ALLOWED_MARKERS:
        raise LockError(f"{context} uses unsupported marker {marker!r}")
    return Requirement(name, version, marker)


def load_manifest(path: Path = MANIFEST) -> tuple[str, dict[str, Profile]]:
    try:
        text = _read_file_bounded(path, MAX_MANIFEST_BYTES, "lock manifest").decode(
            "utf-8"
        )
        payload = _strict_toml_loads(text)
    except (UnicodeDecodeError, tomllib.TOMLDecodeError, ValueError) as error:
        raise LockError(f"cannot read lock manifest: {error}") from error
    if payload.get("schema_version") != 1:
        raise LockError("lock manifest schema_version must be 1")
    index_url = _require_string(payload.get("index_url"), "index_url")
    if index_url != "https://pypi.org/simple":
        raise LockError("index_url must be the canonical HTTPS PyPI simple index")
    raw_profiles = _require_mapping(payload.get("profiles"), "profiles")
    profiles: dict[str, Profile] = {}
    for name, raw_profile in raw_profiles.items():
        if not isinstance(name, str) or not NAME_RE.fullmatch(name):
            raise LockError(f"invalid profile name {name!r}")
        table = _require_mapping(raw_profile, f"profiles.{name}")
        lock_text = _require_string(table.get("lock"), f"profiles.{name}.lock")
        lock = (ROOT / lock_text).resolve()
        if ROOT not in lock.parents or lock.suffix != ".lock":
            raise LockError(f"profiles.{name}.lock escapes the repository or is not .lock")
        raw_includes = table.get("includes")
        raw_requirements = table.get("requirements")
        if not isinstance(raw_includes, list) or not all(
            isinstance(item, str) for item in raw_includes
        ):
            raise LockError(f"profiles.{name}.includes must be a string array")
        if not isinstance(raw_requirements, list):
            raise LockError(f"profiles.{name}.requirements must be an array")
        requirements = tuple(
            _parse_requirement(item, f"profiles.{name}.requirements[{index}]")
            for index, item in enumerate(raw_requirements)
        )
        profiles[name] = Profile(name, lock, tuple(raw_includes), requirements)

    if tuple(profiles) != ("action", "ci", "docs", "release"):
        raise LockError("profiles must be declared in action, ci, docs, release order")
    if profiles["action"].includes:
        raise LockError("action must not include another profile")
    if profiles["ci"].includes != ("action",):
        raise LockError("ci must include exactly action")
    if profiles["docs"].includes:
        raise LockError("docs must not include another profile")
    if profiles["release"].includes != ("action",):
        raise LockError("release must include exactly action")

    seen: dict[str, tuple[str, str]] = {}
    requirement_count = 0
    for profile in profiles.values():
        names = [item.canonical_name for item in profile.requirements]
        if names != sorted(names):
            raise LockError(f"profiles.{profile.name}.requirements must be name-sorted")
        if len(names) != len(set(names)):
            raise LockError(f"profiles.{profile.name} contains duplicate packages")
        for requirement in profile.requirements:
            requirement_count += 1
            if requirement_count > MAX_REQUIREMENTS:
                raise LockError(
                    f"lock manifest exceeds the {MAX_REQUIREMENTS}-requirement limit"
                )
            previous = seen.get(requirement.canonical_name)
            current = (requirement.version, requirement.marker or "")
            if previous is not None and previous != current:
                raise LockError(
                    f"{requirement.name} has conflicting versions or markers across profiles"
                )
            seen[requirement.canonical_name] = current
    return index_url, profiles


def _declared_content_length(response: object, context: str) -> int | None:
    response_attributes = getattr(response, "__dict__", {})
    if (
        "headers" not in response_attributes
        and getattr(type(response), "headers", None) is None
    ):
        return None
    headers = getattr(response, "headers", None)
    if headers is None:
        return None
    get_all = getattr(headers, "get_all", None)
    if callable(get_all):
        values = get_all("Content-Length")
        if values is None:
            return None
        if len(values) != 1:
            raise LockError(f"{context} returned ambiguous Content-Length")
        raw_length: object = values[0]
    else:
        raw_length = headers.get("Content-Length")
        if raw_length is None:
            return None
    if isinstance(raw_length, int) and not isinstance(raw_length, bool):
        length = raw_length
    elif (
        isinstance(raw_length, str)
        and len(raw_length) <= 20
        and raw_length.isascii()
        and raw_length.isdigit()
    ):
        length = int(raw_length)
    else:
        raise LockError(f"{context} returned malformed Content-Length")
    if length < 0:
        raise LockError(f"{context} returned malformed Content-Length")
    return length


def _read_response_bounded(response: object, max_bytes: int, context: str) -> bytes:
    declared = _declared_content_length(response, context)
    if declared is not None and declared > max_bytes:
        raise LockError(f"{context} exceeds the {max_bytes}-byte response limit")
    read_limit = declared if declared is not None else max_bytes
    chunks: list[bytes] = []
    total = 0
    while total < read_limit:
        requested = min(READ_CHUNK_BYTES, read_limit - total)
        chunk = response.read(requested)
        if not isinstance(chunk, bytes):
            raise LockError(f"{context} returned non-byte response data")
        if len(chunk) > requested:
            raise LockError(f"{context} exceeded a bounded read request")
        if not chunk:
            break
        chunks.append(chunk)
        total += len(chunk)
    sentinel = response.read(1)
    if not isinstance(sentinel, bytes):
        raise LockError(f"{context} returned non-byte response data")
    if sentinel:
        limit = declared if declared is not None else max_bytes
        raise LockError(f"{context} exceeds its {limit}-byte response limit")
    if declared is not None and total != declared:
        raise LockError(f"{context} body disagrees with Content-Length")
    return b"".join(chunks)


def _pypi_release(requirement: Requirement) -> list[dict[str, str]]:
    project = urllib.parse.quote(requirement.name, safe="")
    version = urllib.parse.quote(requirement.version, safe="")
    url = f"https://pypi.org/pypi/{project}/{version}/json"
    request = urllib.request.Request(
        url,
        headers={"Accept": "application/json", "User-Agent": "boundver-lock/1"},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = _read_response_bounded(
                response,
                MAX_PYPI_METADATA_BYTES,
                f"PyPI metadata for {requirement.rendered}",
            )
            try:
                payload = _strict_json_loads(body.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as error:
                raise LockError(
                    f"cannot fetch {requirement.rendered} metadata: {error}"
                ) from error
    except (
        OSError,
        urllib.error.URLError,
    ) as error:
        raise LockError(f"cannot fetch {requirement.rendered} metadata: {error}") from error
    if not isinstance(payload, dict):
        raise LockError(f"PyPI returned malformed metadata for {requirement.rendered}")
    info = payload.get("info")
    urls = payload.get("urls")
    if not isinstance(info, dict) or info.get("version") != requirement.version:
        raise LockError(f"PyPI version mismatch for {requirement.rendered}")
    if not isinstance(urls, list):
        raise LockError(f"PyPI returned no artifact list for {requirement.rendered}")
    if len(urls) > MAX_PYPI_FILES:
        raise LockError(
            f"PyPI returned more than {MAX_PYPI_FILES} artifacts for "
            f"{requirement.rendered}"
        )
    artifacts: list[dict[str, str]] = []
    for entry in urls:
        if not isinstance(entry, dict):
            raise LockError(f"PyPI returned a malformed artifact for {requirement.rendered}")
        if entry.get("packagetype") != "bdist_wheel" or entry.get("yanked") is not False:
            continue
        filename = entry.get("filename")
        digests = entry.get("digests")
        download_url = entry.get("url")
        if (
            not isinstance(filename, str)
            or not _wheel_filename_within_limit(filename)
            or Path(filename).name != filename
            or not filename.endswith(".whl")
            or not isinstance(digests, dict)
            or not isinstance(download_url, str)
            or not download_url.startswith("https://files.pythonhosted.org/")
        ):
            raise LockError(f"PyPI returned invalid wheel metadata for {requirement.rendered}")
        digest = digests.get("sha256")
        if not isinstance(digest, str) or HASH_RE.fullmatch(digest) is None:
            raise LockError(f"PyPI wheel lacks SHA-256 for {requirement.rendered}")
        artifacts.append({"filename": filename, "sha256": digest})
    artifacts.sort(key=lambda item: (item["filename"], item["sha256"]))
    if not artifacts:
        raise LockError(f"{requirement.rendered} has no non-yanked wheel on PyPI")
    if len({item["filename"] for item in artifacts}) != len(artifacts):
        raise LockError(f"PyPI returned duplicate wheel names for {requirement.rendered}")
    return artifacts


def _all_requirements(profiles: Mapping[str, Profile]) -> list[Requirement]:
    requirements = [item for profile in profiles.values() for item in profile.requirements]
    return sorted(requirements, key=lambda item: item.canonical_name)


def _artifact_payload(
    profiles: Mapping[str, Profile],
    artifacts: Mapping[str, Sequence[Mapping[str, str]]],
) -> bytes:
    packages: dict[str, object] = {}
    by_name = {item.canonical_name: item for item in _all_requirements(profiles)}
    for canonical_name in sorted(by_name):
        requirement = by_name[canonical_name]
        packages[canonical_name] = {
            "name": requirement.name,
            "version": requirement.version,
            "wheels": list(artifacts[canonical_name]),
        }
    payload = {
        "schema_version": 1,
        "source": "https://pypi.org/pypi/{project}/{version}/json",
        "packages": packages,
    }
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _render_lock(
    profile: Profile,
    profiles: Mapping[str, Profile],
    artifacts: Mapping[str, Sequence[Mapping[str, str]]],
) -> bytes:
    lines = [
        "# Generated by scripts/lock_release_tools.py; DO NOT EDIT.",
        "# Source policy: scripts/release-tool-lock.toml",
        "# Artifact evidence: scripts/release-tool-artifacts.json",
        "--require-hashes",
        "--only-binary :all:",
    ]
    for included_name in profile.includes:
        included = profiles[included_name]
        relative = Path(".") / Path(included.lock.name)
        lines.append(f"-r {relative.as_posix()}")
    if profile.includes:
        lines.append("")
    for requirement in profile.requirements:
        hashes = sorted(
            {item["sha256"] for item in artifacts[requirement.canonical_name]}
        )
        line = requirement.rendered + " \\"
        lines.append(line)
        for index, digest in enumerate(hashes):
            continuation = " \\" if index != len(hashes) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{continuation}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def _generate() -> dict[Path, bytes]:
    _, profiles = load_manifest()
    artifacts: dict[str, list[dict[str, str]]] = {}
    wheel_count = 0
    for requirement in _all_requirements(profiles):
        wheels = _pypi_release(requirement)
        wheel_count += len(wheels)
        if wheel_count > MAX_TOTAL_WHEELS:
            raise LockError(
                f"generated evidence exceeds the {MAX_TOTAL_WHEELS}-wheel limit"
            )
        artifacts[requirement.canonical_name] = wheels
    outputs = {ARTIFACTS: _artifact_payload(profiles, artifacts)}
    outputs.update(
        {
            profile.lock: _render_lock(profile, profiles, artifacts)
            for profile in profiles.values()
        }
    )
    for path, content in outputs.items():
        max_bytes = (
            MAX_ARTIFACT_EVIDENCE_BYTES if path == ARTIFACTS else MAX_LOCK_FILE_BYTES
        )
        if len(content) > max_bytes:
            raise LockError(
                f"generated {path.relative_to(ROOT)} exceeds the {max_bytes}-byte limit"
            )
    return outputs


def _load_artifacts(
    path: Path = ARTIFACTS,
) -> tuple[dict[str, list[dict[str, str]]], dict[str, str]]:
    try:
        body = _read_file_bounded(
            path, MAX_ARTIFACT_EVIDENCE_BYTES, "artifact evidence"
        )
        payload = _strict_json_loads(body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as error:
        raise LockError(f"cannot read artifact evidence: {error}") from error
    if not isinstance(payload, dict) or payload.get("schema_version") != 1:
        raise LockError("artifact evidence schema_version must be 1")
    if payload.get("source") != "https://pypi.org/pypi/{project}/{version}/json":
        raise LockError("artifact evidence has an unexpected source")
    raw_packages = _require_mapping(payload.get("packages"), "artifact packages")
    result: dict[str, list[dict[str, str]]] = {}
    versions: dict[str, str] = {}
    wheel_count = 0
    if len(raw_packages) > MAX_REQUIREMENTS:
        raise LockError(
            f"artifact evidence exceeds the {MAX_REQUIREMENTS}-package limit"
        )
    for canonical_name, raw_package in raw_packages.items():
        if not isinstance(canonical_name, str):
            raise LockError("artifact package name must be a string")
        package = _require_mapping(raw_package, f"artifacts.{canonical_name}")
        name = _require_string(package.get("name"), f"artifacts.{canonical_name}.name")
        version = _require_string(
            package.get("version"), f"artifacts.{canonical_name}.version"
        )
        if re.sub(r"[-_.]+", "-", name).lower() != canonical_name:
            raise LockError(f"artifact canonical name mismatch for {name}")
        raw_wheels = package.get("wheels")
        if not isinstance(raw_wheels, list) or not raw_wheels:
            raise LockError(f"artifacts.{canonical_name}.wheels must be non-empty")
        wheel_count += len(raw_wheels)
        if wheel_count > MAX_TOTAL_WHEELS:
            raise LockError(
                f"artifact evidence exceeds the {MAX_TOTAL_WHEELS}-wheel limit"
            )
        wheels: list[dict[str, str]] = []
        for raw_wheel in raw_wheels:
            wheel = _require_mapping(raw_wheel, f"artifacts.{canonical_name}.wheel")
            filename = _require_string(wheel.get("filename"), "wheel filename")
            digest = _require_string(wheel.get("sha256"), "wheel sha256")
            if (
                not _wheel_filename_within_limit(filename)
                or Path(filename).name != filename
                or not filename.endswith(".whl")
            ):
                raise LockError(f"invalid wheel filename {filename!r}")
            if HASH_RE.fullmatch(digest) is None:
                raise LockError(f"invalid wheel SHA-256 for {filename}")
            wheels.append({"filename": filename, "sha256": digest})
        if wheels != sorted(wheels, key=lambda item: (item["filename"], item["sha256"])):
            raise LockError(f"artifacts.{canonical_name}.wheels is not sorted")
        if len({item["filename"] for item in wheels}) != len(wheels):
            raise LockError(f"artifacts.{canonical_name} has duplicate wheel names")
        result[canonical_name] = wheels
        versions[canonical_name] = version
    return result, versions


def verify() -> None:
    _, profiles = load_manifest()
    artifacts, artifact_versions = _load_artifacts()
    requirements = _all_requirements(profiles)
    expected_names = {item.canonical_name for item in requirements}
    actual_names = set(artifacts)
    if actual_names != expected_names:
        raise LockError(
            "artifact package set differs from manifest: "
            f"missing={sorted(expected_names - actual_names)}, "
            f"extra={sorted(actual_names - expected_names)}"
        )
    for requirement in requirements:
        if artifact_versions.get(requirement.canonical_name) != requirement.version:
            raise LockError(f"artifact version differs for {requirement.name}")
    expected_artifact_bytes = _artifact_payload(profiles, artifacts)
    if not _file_matches(
        ARTIFACTS,
        expected_artifact_bytes,
        MAX_ARTIFACT_EVIDENCE_BYTES,
        "artifact evidence",
    ):
        raise LockError("artifact evidence is not canonical")
    for profile in profiles.values():
        expected = _render_lock(profile, profiles, artifacts)
        relative = profile.lock.relative_to(ROOT)
        if not _file_matches(
            profile.lock,
            expected,
            MAX_LOCK_FILE_BYTES,
            str(relative),
        ):
            raise LockError(f"{profile.lock.relative_to(ROOT)} differs from its manifest")


def _write(outputs: Mapping[Path, bytes]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        print(f"wrote {path.relative_to(ROOT)}")


def _check(outputs: Mapping[Path, bytes]) -> None:
    stale = []
    for path, expected in outputs.items():
        max_bytes = (
            MAX_ARTIFACT_EVIDENCE_BYTES if path == ARTIFACTS else MAX_LOCK_FILE_BYTES
        )
        if not _file_matches(
            path,
            expected,
            max_bytes,
            str(path.relative_to(ROOT)),
            missing_is_mismatch=True,
        ):
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        raise LockError("generated lock files are stale: " + ", ".join(stale))


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("generate", "verify", "check"))
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "verify":
            verify()
        else:
            outputs = _generate()
            if args.command == "generate":
                _write(outputs)
                verify()
            else:
                _check(outputs)
    except LockError as error:
        print(f"release tool lock error: {error}", file=sys.stderr)
        return 1
    print(f"release tool lock {args.command} passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
